apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-epick-book
  labels:
    app: epick-book
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: epick-book
  template:
    metadata:
      labels:
        app: epick-book
    spec:
      containers:
        - name: epick-book
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}