apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-epick-book-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: epick-book
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}