apiVersion: v1
kind: PersistentVolume
metadata:
  name: epick-book-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/epick-book"    # folder on the Kind node