apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: epick-book-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi       # requesting 500MB from the 1GB PV