apiVersion: v1
kind: Pod
metadata:
  name: epick-book-selective
  labels:
    app: epick-book
spec:
  containers:
    - name: epick-book-container
      image: nginx
      env:
        - name: MY_APP_ENV         # name inside the container
          valueFrom:
            configMapKeyRef:
              name: app-config     # ConfigMap name
              key: APP_ENV         # specific key to pull

        - name: MY_APP_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_PORT

        - name: MY_DB_PASSWORD     # name inside the container
          valueFrom:
            secretKeyRef:
              name: app-secret     # Secret name
              key: DB_PASSWORD     # specific key to pull